In [1]:
import numpy as np

# Q1
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Q1:")
print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {type(array_list)}\n")

Q1:
Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>



In [2]:
# Q2
print("Q2:")
print("Data types of each element in list_:")
for element in list_:
    print(type(element))

print("\nData types of each element in array_list:")
for element in array_list:
    print(type(element))

Q2:
Data types of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
# Q3
array_list = np.array(object=list_, dtype=int)

print("\nQ3:")
print("Data types of each element in list_ (after conversion):")
for element in list_:
    print(type(element))

print("\nData types of each element in array_list (after conversion):")
for element in array_list:
    print(type(element))

# New section for Q4 onwards



Q3:
Data types of each element in list_ (after conversion):
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of each element in array_list (after conversion):
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [4]:
# Q4
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print("\nQ4:")
print(f"Shape of num_array: {num_array.shape}")
print(f"Size of num_array: {num_array.size}\n")



Q4:
Shape of num_array: (2, 3)
Size of num_array: 6



In [5]:
# Q5
print("Q5:")
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

Q5:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Q6
print("\nQ6:")
identity_matrix = np.eye(5)
print(identity_matrix)


Q6:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
